controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # joint_trajectory_controller:
    ar3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

# joint_trajectory_controller:
ar3_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
      # Might need to add 'velocity' command interface
    state_interfaces:
      - position
      # [ros2_control_node-5] [ERROR] [1628544997.578343145] [controller_manager]: 
      # Can't activate controller 'ar3_arm_controller': State interface with key 'ar3_joint1/velocity' does not exist
      # - velocity 
    joints:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6
